### ISSUE TITLE
Tracking issue: lint settings

### ISSUE THREAD

**Issue by jpeddicord** [amzn/oss-contribution-tracker#30]
* [x] Update tslint settings
* [x] Add prettier, run on `npm lint`
* [ ] Swap to `undefined` over `null` (general TypeScript-y convention, but has nice semantics for types like `?` and other optional things)
* [ ] Remove `jsx-no-lambda` suppressor
* [x] Travis CI lint check
* [x] Protected branches

**Comment by jamesiri** [comment]
#73
